"""Periodic-net dimensionality: the rank of the cycle lattice.

Extracted from queries/dimensionality_net.py so that ingest/build_graph.py can
stamp the result onto every Structure node at build time. Having it as a node
property is what lets the UI ask "show me the 2D sheets" as a one-line MATCH
instead of shipping a Python script alongside the demo.

Why the naive traversal is wrong
--------------------------------
The contact edges we store form a *quotient* graph: nodes are asymmetric-unit
sites and each edge carries the symmetry operation that generated the
neighbour. A hydrogen-bonded chain running through the crystal is therefore NOT
a long path in that graph -- it is a short cycle, because after a few hops you
return to the same asymmetric-unit site one unit cell over. Counting reachable
nodes by depth saturates immediately and reports every structure as isolated.

The correct method is the standard periodic-net calculation. Build the labelled
quotient graph of the full unit cell, where every edge carries the integer
lattice vector crossed when traversing it. Take a spanning tree; for every
non-tree edge compute the net lattice translation around the cycle it closes.
The **rank of the set of those translations** is the dimensionality:

    rank 0  ->  0D  finite motif (dimer, ring, isolated cluster)
    rank 1  ->  1D  chain
    rank 2  ->  2D  sheet
    rank 3  ->  3D  framework

This is precisely what the symop on every edge is for: it decides the
dimensionality of an infinite periodic network without ever materialising a
supercell.
"""

from __future__ import annotations

from collections import defaultdict

import gemmi
import numpy as np

LABELS = {0: "0D finite motif", 1: "1D chain", 2: "2D sheet", 3: "3D framework"}
CONSEQUENCE = {
    0: "isolated dimers/clusters - typically the most soluble",
    1: "chains - often needle morphology, anisotropic mechanical response",
    2: "layers - plate morphology, easy cleavage, good tabletting",
    3: "three-dimensional network - harder, less soluble, humidity stable",
}


def _compose(g: gemmi.Op, s: gemmi.Op) -> tuple[np.ndarray, np.ndarray]:
    """Compose g after s, KEEPING the lattice part of the translation.

    gemmi's own `g * s` reduces the translation modulo one unit cell, which
    silently discards exactly the information this calculation depends on:

        S        = -x,-y+1,-z   tran [0, 24, 0]
        g[0] * S = -x,-y,-z     tran [0,  0, 0]    <- the +1 in y is gone

    With every lattice translation flattened to zero, every cycle closes with a
    zero period and every structure looks 0D. So we do the composition in exact
    integer arithmetic instead. gemmi scales both rot and tran by Op.DEN, so
    with R = rot/DEN an integer rotation matrix:

        rot(g.s)  = R_g @ rot_s          (still DEN-scaled)
        tran(g.s) = R_g @ tran_s + tran_g (still DEN-scaled, NOT reduced)
    """
    den = gemmi.Op.DEN
    rg = np.array(g.rot, dtype=np.int64) // den
    rot = rg @ np.array(s.rot, dtype=np.int64)
    tran = rg @ np.array(s.tran, dtype=np.int64) + np.array(g.tran, dtype=np.int64)
    return rot, tran


def _decompose(
    rot: np.ndarray, tran: np.ndarray, ops: list[gemmi.Op]
) -> tuple[int, tuple[int, int, int]] | None:
    """Write (rot, tran) as ops[k] followed by an integer lattice translation."""
    den = gemmi.Op.DEN
    for k, op in enumerate(ops):
        if not np.array_equal(np.array(op.rot, dtype=np.int64), rot):
            continue
        d = tran - np.array(op.tran, dtype=np.int64)
        if np.all(d % den == 0):
            q = d // den
            return k, (int(q[0]), int(q[1]), int(q[2]))
    return None


def _op_from_code(code: str, ops: list[gemmi.Op]) -> gemmi.Op:
    idx_s, tr_s = code.split("_")
    base = ops[int(idx_s) - 1]
    op = gemmi.Op(base.triplet())
    den = gemmi.Op.DEN
    sh = [int(c) - 5 for c in tr_s]
    op.tran = (op.tran[0] + sh[0] * den,
               op.tran[1] + sh[1] * den,
               op.tran[2] + sh[2] * den)
    return op


def net_dimensionality(
    spacegroup_number: int,
    contacts: list[tuple[str, str, str]],
    uid_to_site: dict[str, int],
) -> tuple[int, int, int]:
    """Return (dimensionality, n_nodes_in_largest_component, n_components).

    `contacts` is [(a_uid, b_uid, symop_code)]; a_uid sits at the identity and
    b_uid is generated by symop_code.
    """
    sg = gemmi.find_spacegroup_by_number(spacegroup_number)
    if sg is None or not contacts:
        return 0, 0, 0
    ops = list(sg.operations())
    n_ops = len(ops)
    # Hard ceiling on the orbit expansion. A hang here is disproportionately
    # expensive -- it stalls a whole-corpus ingest with no error -- so an
    # over-large structure is declined rather than attempted.
    if len(contacts) * n_ops * n_ops > 4_000_000:
        return -1, 0, 0

    # Unit-cell nodes are (asymmetric site, symmetry operation). Applying every
    # operation g to a stored edge gives the whole orbit of that contact.
    adj: dict[tuple[int, int], list[tuple[tuple[int, int], np.ndarray]]] = defaultdict(list)
    for a_uid, b_uid, code in contacts:
        a = uid_to_site.get(a_uid)
        b = uid_to_site.get(b_uid)
        if a is None or b is None:
            continue
        try:
            s_op = _op_from_code(code, ops)
        except Exception:  # noqa: BLE001
            continue
        for g_idx, g in enumerate(ops):
            c_rot, c_tran = _compose(g, s_op)
            got = _decompose(c_rot, c_tran, ops)
            if got is None:
                continue
            k, tau = got
            v = np.array(tau, dtype=np.int64)
            adj[(a, g_idx)].append(((b, k), v))
            adj[(b, k)].append(((a, g_idx), -v))

    if not adj:
        return 0, 0, 0

    # spanning forest with accumulated lattice potentials; every non-tree edge
    # closes a cycle whose net translation is a period of the net.
    #
    # Cycles are collected as a SET of integer triples, not a list. A dense net
    # closes one cycle per non-tree edge -- hundreds of thousands of them on a
    # well-connected structure once weak C-H...A contacts are admitted -- and
    # feeding all of those to matrix_rank builds an enormous (n x 3) matrix
    # whose rank can only ever be 0..3. Worse, it spends that time inside LAPACK
    # with the GIL released, so the ingest's SIGALRM watchdog cannot fire and a
    # single structure can hang the whole run at 100% CPU with no diagnostic.
    #
    # De-duplicating is exact -- rank depends on the SET of vectors, not on how
    # many times each appears -- and collapses those hundreds of thousands to a
    # handful of distinct primitive translations.
    seen: dict[tuple[int, int], np.ndarray] = {}
    cycle_set: set[tuple[int, int, int]] = set()
    comp_sizes: list[int] = []
    for start in list(adj):
        if start in seen:
            continue
        seen[start] = np.zeros(3, dtype=np.int64)
        stack = [start]
        size = 0
        while stack:
            u = stack.pop()
            size += 1
            for v, t in adj.get(u, ()):
                if v not in seen:
                    seen[v] = seen[u] + t
                    stack.append(v)
                else:
                    cyc = seen[u] + t - seen[v]
                    if cyc.any():
                        cycle_set.add((int(cyc[0]), int(cyc[1]), int(cyc[2])))
        comp_sizes.append(size)

    if not cycle_set:
        return 0, max(comp_sizes, default=0), len(comp_sizes)
    rank = int(np.linalg.matrix_rank(
        np.array(sorted(cycle_set), dtype=np.float64)
    ))
    return min(rank, 3), max(comp_sizes, default=0), len(comp_sizes)


def is_involution(triplet: str) -> bool:
    """True if applying this symmetry operation twice is the identity EXACTLY.

    This is the discriminator between a ring motif and a catemer, and it is the
    thing that decides whether an R2,2(8) acid dimer query is right or wrong.

    A centrosymmetric dimer is generated by an inversion, a mirror or a
    two-fold: S o S is the identity with a ZERO lattice translation, the
    operation has order 2, and it relates exactly two molecules. A catemer is
    generated by a 2(1) screw, a glide or a pure translation: S o S is a
    NON-ZERO lattice translation, the operation has infinite order, and it
    generates a chain.

    Both have a two-fold rotation part, so testing the rotation alone does not
    separate them -- the translation is the whole signal, which is why this
    uses the exact integer composition from `_compose` rather than gemmi's
    `g * s` (that reduces the translation modulo one cell and would call a
    screw axis an involution).
    """
    try:
        op = gemmi.Op(triplet)
    except Exception:  # noqa: BLE001
        return False
    rot, tran = _compose(op, op)
    # _compose returns gemmi's DEN-scaled integers, so the identity rotation is
    # DEN * I, not I.
    den = gemmi.Op.DEN
    identity = np.eye(3, dtype=np.int64) * den
    return bool(np.array_equal(rot, identity) and not tran.any())
