"""Hydrogen-bond network dimensionality, done the way a crystallographer would.

Why the naive traversal is wrong
--------------------------------
The contact edges we store form a *quotient graph*: the nodes are
asymmetric-unit sites and each edge carries the symmetry operation that
generated the neighbour. A hydrogen-bonded chain running through the crystal is
therefore NOT a long path in that graph -- it is a short cycle, because after a
few hops you come back to the same asymmetric-unit site one unit cell over.
Counting reachable nodes at increasing depth saturates almost immediately and
reports every structure as "isolated", which is exactly what it did.

The correct method
------------------
This is the standard periodic-net calculation. Build the labelled quotient graph
of the full unit cell, where every edge carries the integer lattice vector you
cross when you traverse it. Take a spanning tree, and for every non-tree edge
compute the net lattice translation around the cycle it closes. The **rank of
the set of those translation vectors** is the dimensionality of the net:

    rank 0  ->  0D  finite motif (dimer, ring, isolated cluster)
    rank 1  ->  1D  chain
    rank 2  ->  2D  sheet
    rank 3  ->  3D  framework

This is precisely what the `symop` on every edge is *for*: it lets us decide the
dimensionality of an infinite periodic network without ever materialising a
supercell. It is also a real crystallographic result -- dimensionality predicts
morphology (chains give needles, sheets give plates), cleavage and tabletting
behaviour, and correlates with solubility and humidity stability.

Runs over the ingest cache so it needs no re-parse.

Usage:
    uv run python queries/dimensionality_net.py --limit 5000
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Sequence

import gemmi
import numpy as np

LABELS = {0: "0D finite motif", 1: "1D chain", 2: "2D sheet", 3: "3D framework"}
CONSEQUENCE = {
    0: "isolated dimers/clusters - typically the most soluble",
    1: "chains - often needle morphology, anisotropic mechanical response",
    2: "layers - plate morphology, easy cleavage, good tabletting",
    3: "three-dimensional network - harder, less soluble, humidity stable",
}


def _compose(g: gemmi.Op, s: gemmi.Op) -> tuple[np.ndarray, np.ndarray]:
    """Compose g after s, KEEPING the lattice part of the translation.

    gemmi's own `g * s` reduces the translation modulo one unit cell, which
    silently discards exactly the information this calculation depends on:

        S        = -x,-y+1,-z   tran [0, 24, 0]
        g[0] * S = -x,-y,-z     tran [0,  0, 0]    <- the +1 in y is gone

    With every lattice translation flattened to zero, every cycle closes with a
    zero period and every structure looks 0D. So we do the composition in exact
    integer arithmetic instead. gemmi scales both rot and tran by Op.DEN, so
    with R = rot/DEN an integer rotation matrix:

        rot(g.s)  = R_g @ rot_s          (still DEN-scaled)
        tran(g.s) = R_g @ tran_s + tran_g (still DEN-scaled, NOT reduced)
    """
    den = gemmi.Op.DEN
    rg = np.array(g.rot, dtype=np.int64) // den
    rot = rg @ np.array(s.rot, dtype=np.int64)
    tran = rg @ np.array(s.tran, dtype=np.int64) + np.array(g.tran, dtype=np.int64)
    return rot, tran


def _decompose(
    rot: np.ndarray, tran: np.ndarray, ops: list[gemmi.Op]
) -> tuple[int, tuple[int, int, int]] | None:
    """Write (rot, tran) as ops[k] followed by an integer lattice translation."""
    den = gemmi.Op.DEN
    for k, op in enumerate(ops):
        if not np.array_equal(np.array(op.rot, dtype=np.int64), rot):
            continue
        d = tran - np.array(op.tran, dtype=np.int64)
        if np.all(d % den == 0):
            q = d // den
            return k, (int(q[0]), int(q[1]), int(q[2]))
    return None


def _op_from_code(code: str, ops: list[gemmi.Op]) -> gemmi.Op:
    idx_s, tr_s = code.split("_")
    base = ops[int(idx_s) - 1]
    op = gemmi.Op(base.triplet())
    den = gemmi.Op.DEN
    sh = [int(c) - 5 for c in tr_s]
    op.tran = (op.tran[0] + sh[0] * den,
               op.tran[1] + sh[1] * den,
               op.tran[2] + sh[2] * den)
    return op


def net_dimensionality(
    spacegroup_number: int,
    contacts: list[tuple[str, str, str]],
    uid_to_site: dict[str, int],
) -> tuple[int, int, int]:
    """Return (dimensionality, n_nodes_in_largest_component, n_components).

    `contacts` is [(a_uid, b_uid, symop_code)]; a_uid sits at the identity and
    b_uid is generated by symop_code.
    """
    sg = gemmi.find_spacegroup_by_number(spacegroup_number)
    if sg is None or not contacts:
        return 0, 0, 0
    ops = list(sg.operations())
    n_ops = len(ops)

    # Unit-cell nodes are (asymmetric site, symmetry operation). Applying every
    # operation g to a stored edge gives the whole orbit of that contact.
    adj: dict[tuple[int, int], list[tuple[tuple[int, int], np.ndarray]]] = defaultdict(list)
    for a_uid, b_uid, code in contacts:
        a = uid_to_site.get(a_uid)
        b = uid_to_site.get(b_uid)
        if a is None or b is None:
            continue
        try:
            s_op = _op_from_code(code, ops)
        except Exception:  # noqa: BLE001
            continue
        for g_idx, g in enumerate(ops):
            c_rot, c_tran = _compose(g, s_op)
            got = _decompose(c_rot, c_tran, ops)
            if got is None:
                continue
            k, tau = got
            v = np.array(tau, dtype=np.int64)
            adj[(a, g_idx)].append(((b, k), v))
            adj[(b, k)].append(((a, g_idx), -v))

    if not adj:
        return 0, 0, 0

    # spanning forest with accumulated lattice potentials; every non-tree edge
    # closes a cycle whose net translation is a period of the net
    seen: dict[tuple[int, int], np.ndarray] = {}
    cycles: list[np.ndarray] = []
    comp_sizes: list[int] = []
    for start in list(adj):
        if start in seen:
            continue
        seen[start] = np.zeros(3, dtype=np.int64)
        stack = [start]
        size = 0
        while stack:
            u = stack.pop()
            size += 1
            for v, t in adj.get(u, ()):
                if v not in seen:
                    seen[v] = seen[u] + t
                    stack.append(v)
                else:
                    cyc = seen[u] + t - seen[v]
                    if cyc.any():
                        cycles.append(cyc)
        comp_sizes.append(size)

    if not cycles:
        return 0, max(comp_sizes, default=0), len(comp_sizes)
    rank = int(np.linalg.matrix_rank(np.array(cycles, dtype=np.float64)))
    return min(rank, 3), max(comp_sizes, default=0), len(comp_sizes)


def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--cache", type=Path,
                    default=Path("data/jsonl/cod_slice.cache.jsonl"))
    ap.add_argument("--limit", type=int, default=None)
    ap.add_argument("--include-inferred", action="store_true",
                    help="include hydrogen bonds with no located hydrogen")
    ap.add_argument("--out", type=Path,
                    default=Path("data/manifest/dimensionality.json"))
    args = ap.parse_args(argv)

    if not args.cache.exists():
        print(f"missing {args.cache}", file=sys.stderr)
        return 1

    dist: Counter[int] = Counter()
    examples: dict[int, list[tuple[int, str, int]]] = defaultdict(list)
    rows: list[dict] = []
    n = 0

    with args.cache.open() as fh:
        for line in fh:
            if args.limit and n >= args.limit:
                break
            try:
                res = json.loads(line)
            except json.JSONDecodeError:
                continue
            if res.get("skipped") or not res.get("contacts"):
                continue
            uid_to_site = {a["uid"]: i for i, a in enumerate(res["atoms"])}
            contacts = [
                (c["a"], c["b"], c["symop"])
                for c in res["contacts"]
                if c["kind"] == "hbond"
                and (args.include_inferred or not c["h_inferred"])
            ]
            if not contacts:
                continue
            dim, biggest, ncomp = net_dimensionality(
                res["spacegroup_number"], contacts, uid_to_site
            )
            n += 1
            dist[dim] += 1
            rows.append({
                "cod_id": res["cod_id"], "dimensionality": dim,
                "hm": res["spacegroup_hm"], "n_hbonds": len(contacts),
            })
            if len(examples[dim]) < 5:
                examples[dim].append(
                    (res["cod_id"], res["spacegroup_hm"], len(contacts))
                )

    print(f"structures with at least one located-H hydrogen bond: {n:,}")
    print(f"(inferred-H bonds {'INCLUDED' if args.include_inferred else 'excluded'} "
          f"- a motif claim resting on unrefined hydrogens would not survive review)\n")
    print(f"{'dimensionality':<20}{'structures':>12}{'share':>9}   consequence")
    print("-" * 96)
    for d in (0, 1, 2, 3):
        c = dist.get(d, 0)
        print(f"{LABELS[d]:<20}{c:>12,}{100 * c / max(n, 1):>8.1f}%   {CONSEQUENCE[d]}")

    print("\nexamples:")
    for d in (0, 1, 2, 3):
        for cod, hm, nb in examples.get(d, [])[:3]:
            print(f"  {LABELS[d]:<18} COD {cod:<9} {hm:<14} {nb} H-bonds")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(
        {"counts": {LABELS[k]: v for k, v in sorted(dist.items())},
         "n_structures": n, "include_inferred": args.include_inferred,
         "per_structure": rows}, indent=2) + "\n")
    print(f"\nwrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
